language: objective-c
matrix:
  include:
    - osx_image: xcode8

script:
  - xcodebuild -project TryUserNotifications.xcodeproj -scheme Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' test
