osx_image: xcode8
language: objective-c
script:
  - xcodebuild -project TryUserNotifications.xcodeproj -scheme Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' test
